site_name: Heracles
site_url: https://heracles.readthedocs.io
nav:
  - Home: index.md
  - API: api.md
theme:
  name: material
  palette:
    # palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins:
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            # general
            allow_inspection: false
            show_bases: false
            show_source: false
            # headings
            show_category_heading: true
            show_object_full_path: false
            show_root_toc_entry: true
            # members
            filters: ["!^__?"]
            inherited_members: true
            show_submodules: false
            # docstrings
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            merge_init_into_class: true
            show_if_no_docstring: true
            # signatures
            line_length: 80
            show_signature: false
  - search
