name: Pull Request Review

on:
  pull_request_review:
    types:
      - submitted

jobs:
  approved:
    name: Approved
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add Reviewed-By
        uses: ntessore/add-reviewed-by-action@v1
